/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchSymbolRouteImport } from './routes/research.$symbol'

const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchSymbolRoute = ResearchSymbolRouteImport.update({
  id: '/$symbol',
  path: '/$symbol',
  getParentRoute: () => ResearchRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ideas': typeof IdeasRoute
  '/journal': typeof JournalRoute
  '/research': typeof ResearchRouteWithChildren
  '/screener': typeof ScreenerRoute
  '/research/$symbol': typeof ResearchSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ideas': typeof IdeasRoute
  '/journal': typeof JournalRoute
  '/research': typeof ResearchRouteWithChildren
  '/screener': typeof ScreenerRoute
  '/research/$symbol': typeof ResearchSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ideas': typeof IdeasRoute
  '/journal': typeof JournalRoute
  '/research': typeof ResearchRouteWithChildren
  '/screener': typeof ScreenerRoute
  '/research/$symbol': typeof ResearchSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ideas'
    | '/journal'
    | '/research'
    | '/screener'
    | '/research/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ideas'
    | '/journal'
    | '/research'
    | '/screener'
    | '/research/$symbol'
  id:
    | '__root__'
    | '/'
    | '/ideas'
    | '/journal'
    | '/research'
    | '/screener'
    | '/research/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdeasRoute: typeof IdeasRoute
  JournalRoute: typeof JournalRoute
  ResearchRoute: typeof ResearchRouteWithChildren
  ScreenerRoute: typeof ScreenerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$symbol': {
      id: '/research/$symbol'
      path: '/$symbol'
      fullPath: '/research/$symbol'
      preLoaderRoute: typeof ResearchSymbolRouteImport
      parentRoute: typeof ResearchRoute
    }
  }
}

interface ResearchRouteChildren {
  ResearchSymbolRoute: typeof ResearchSymbolRoute
}

const ResearchRouteChildren: ResearchRouteChildren = {
  ResearchSymbolRoute: ResearchSymbolRoute,
}

const ResearchRouteWithChildren = ResearchRoute._addFileChildren(
  ResearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdeasRoute: IdeasRoute,
  JournalRoute: JournalRoute,
  ResearchRoute: ResearchRouteWithChildren,
  ScreenerRoute: ScreenerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
